### ISSUE TITLE
Shall we rename to LastMinuteCoders/ctf-writeups ?

### ISSUE THREAD

**Issue by gmacario** [LastMinuteCoders/csc2021-training#13]
Now that the [Reply Cyber Security Challenge]() is over @GGn0 and I were considering to refactor this public repo, making it more general, reorganizing it like [similar repos already available on GitHub](https://github.com/topics/ctf-writeups).

By doing this we may continue to use it to host our writeups of past and future challenges.

Here is question to all LastMinuteCoders members: How about renaming it to LastMinuteCoders/ctf-writeups ?

Please comment here, thanks

**Comment by alv67** [comment]
OK

**Comment by gmacario** [comment]
Thanks @alv67. How about you, @gteti?

**Comment by gteti** [comment]
👍

**Comment by gmacario** [comment]
Thanks.

Repository renamed to <https://github.com/LastMinuteCoders/ctf-writeups>
